/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as ApiCliWalletIndexRouteImport } from './routes/api/cli/wallet/index'
import { Route as ApiCliWalletCreateRouteImport } from './routes/api/cli/wallet/create'
import { Route as ApiCliAuthOtpVerifyRouteImport } from './routes/api/cli/auth/otp/verify'
import { Route as ApiCliAuthOtpRequestRouteImport } from './routes/api/cli/auth/otp/request'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiCliWalletIndexRoute = ApiCliWalletIndexRouteImport.update({
  id: '/api/cli/wallet/',
  path: '/api/cli/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliWalletCreateRoute = ApiCliWalletCreateRouteImport.update({
  id: '/api/cli/wallet/create',
  path: '/api/cli/wallet/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAuthOtpVerifyRoute = ApiCliAuthOtpVerifyRouteImport.update({
  id: '/api/cli/auth/otp/verify',
  path: '/api/cli/auth/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAuthOtpRequestRoute = ApiCliAuthOtpRequestRouteImport.update({
  id: '/api/cli/auth/otp/request',
  path: '/api/cli/auth/otp/request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/cli/wallet/create': typeof ApiCliWalletCreateRoute
  '/api/cli/wallet/': typeof ApiCliWalletIndexRoute
  '/api/cli/auth/otp/request': typeof ApiCliAuthOtpRequestRoute
  '/api/cli/auth/otp/verify': typeof ApiCliAuthOtpVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/cli/wallet/create': typeof ApiCliWalletCreateRoute
  '/api/cli/wallet': typeof ApiCliWalletIndexRoute
  '/api/cli/auth/otp/request': typeof ApiCliAuthOtpRequestRoute
  '/api/cli/auth/otp/verify': typeof ApiCliAuthOtpVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/cli/wallet/create': typeof ApiCliWalletCreateRoute
  '/api/cli/wallet/': typeof ApiCliWalletIndexRoute
  '/api/cli/auth/otp/request': typeof ApiCliAuthOtpRequestRoute
  '/api/cli/auth/otp/verify': typeof ApiCliAuthOtpVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/projects'
    | '/auth/'
    | '/dashboard/'
    | '/api/cli/wallet/create'
    | '/api/cli/wallet/'
    | '/api/cli/auth/otp/request'
    | '/api/cli/auth/otp/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/projects'
    | '/auth'
    | '/dashboard'
    | '/api/cli/wallet/create'
    | '/api/cli/wallet'
    | '/api/cli/auth/otp/request'
    | '/api/cli/auth/otp/verify'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/projects'
    | '/auth/'
    | '/dashboard/'
    | '/api/cli/wallet/create'
    | '/api/cli/wallet/'
    | '/api/cli/auth/otp/request'
    | '/api/cli/auth/otp/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  ApiCliWalletCreateRoute: typeof ApiCliWalletCreateRoute
  ApiCliWalletIndexRoute: typeof ApiCliWalletIndexRoute
  ApiCliAuthOtpRequestRoute: typeof ApiCliAuthOtpRequestRoute
  ApiCliAuthOtpVerifyRoute: typeof ApiCliAuthOtpVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/cli/wallet/': {
      id: '/api/cli/wallet/'
      path: '/api/cli/wallet'
      fullPath: '/api/cli/wallet/'
      preLoaderRoute: typeof ApiCliWalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/wallet/create': {
      id: '/api/cli/wallet/create'
      path: '/api/cli/wallet/create'
      fullPath: '/api/cli/wallet/create'
      preLoaderRoute: typeof ApiCliWalletCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/auth/otp/verify': {
      id: '/api/cli/auth/otp/verify'
      path: '/api/cli/auth/otp/verify'
      fullPath: '/api/cli/auth/otp/verify'
      preLoaderRoute: typeof ApiCliAuthOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/auth/otp/request': {
      id: '/api/cli/auth/otp/request'
      path: '/api/cli/auth/otp/request'
      fullPath: '/api/cli/auth/otp/request'
      preLoaderRoute: typeof ApiCliAuthOtpRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  ApiCliWalletCreateRoute: ApiCliWalletCreateRoute,
  ApiCliWalletIndexRoute: ApiCliWalletIndexRoute,
  ApiCliAuthOtpRequestRoute: ApiCliAuthOtpRequestRoute,
  ApiCliAuthOtpVerifyRoute: ApiCliAuthOtpVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
